import type { Metadata } from 'next'
import '@/style/globals.css'
import '@/style/buttonStyle.css'
import Navigation from '@/components/Sections/Nav/Navigation'
import AnimationProvider from '@/components/provider/AnimationProvider'
import TopLoadingBarProvider from '@/components/provider/TopLoadingBarProvider'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{scrollBehavior:'smooth'}}>


        <body className='body bg_primary text-text-color overflow-x-hidden'>
        <video className="bg-video" src="assests/background.mp4" autoPlay loop muted></video>
          {/* <img src="/assests/bg_gradient_1.png" alt="" className='bg_gradient_image' /> */}
          {/* <img src="/assests/bg_gradient.png" alt="" className='bg_gradient_image_2' /> */}

          
          <Navigation />
      <TopLoadingBarProvider>
          <AnimationProvider>
            {children}
          </AnimationProvider>
     </TopLoadingBarProvider>
        </body>
    </html>
  )
}


function Loading() {
  // You can add any UI inside Loading, including a Skeleton.
  return (
    <main className="page_main flex_center flex-col">
    <section className="flex_center page_main flex-col text-center h-full">
        <div className="flex">
      <h1 className="text_primary_gradient text_sub_heading_size">Fallback Loading...</h1>
        </div>
    </section>
  </main>
  )
}
