import type { Metadata } from 'next'
import ThirdWebProvider from '@/components/provider/ThirdWebProvider'
import '@/style/globals.css'
import Web3ConnectionWrapper from '@/web3Connection/Web3ConnectionContext'
import Navigation from '@/components/Sections/Nav/Navigation'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='body bg_primary text-text-color'>
              <img src="/assests/bg_gradient.png" alt="" className='bg_gradient_image'/>
              <Navigation />
              {children}
              <img src="/assests/bg_gradient.png" alt="" className='bg_gradient_image_2'/>
      </body>
    </html>
  )
}
